project:
  type: website
  title: "Tile Distribution Documentation"
  output-dir: _site

extensions: [r-wasm/live]

website:
  sidebar:
    style: "docked"
    collapse-level: 2
    contents:
      - section: "Getting Started"
        contents:
          - index.qmd
      - section: "Foundation"
        contents:
          - concepts/00_introduction_motivation.qmd
          - concepts/01_buffer_view.qmd
          - concepts/01_tensor_view.qmd
      - section: "Transformation Engine"
        contents:
          - concepts/02_tensor_coordinates.qmd
          - concepts/02_transforms.qmd
          - concepts/02_adaptors.qmd
          - concepts/02_descriptors.qmd
          - concepts/02_convolution_example.qmd
          - concepts/02_coordinate_movement.qmd
      - section: "Distribution API"
        contents:
          - concepts/03_tile_distribution.qmd
          - concepts/03_tile_window.qmd
          - concepts/03_sweep_tile.qmd
      - section: "Coordinate Systems"
        contents:
          - concepts/04_coordinate_systems.qmd
      - section: "Implementation Deep Dive"
        contents:
          - concepts/05_encoding_internals.qmd
          - concepts/05_static_distributed_tensor.qmd
      - section: "Thread Mapping"
        contents:
          - concepts/06_thread_mapping.qmd

format:
  live-html:
    theme:
      light: [litera, custom-theme.scss]
      dark: [slate, custom-theme.scss]
    toc: true
    code-tools: true
    execute:
      eval: false
    link-external-newwindow: true
    code-copy: true
    anchor-sections: true
    mermaid:
      theme: default
    css: 
      - global-font-override.css
      - diagram-sizing-fixes.css
    include-in-header:
      - mermaid-include.html
    include-after-body:
      - text: |
          <script src="font-cleanup.js"></script>

pyodide:
  packages:
    - numpy
    - pandas
    - sympy
    - micropip
  cell-options:
    autorun: false 